#!/usr/bin/env python3
"""Render TTF glyphs into packed 1-bit bitmap fonts for the e-paper driver.

Emits an Adafruit-GFX-compatible layout: glyph bitmaps are bit-packed MSB
first, running continuously across rows, with per-glyph metrics.
"""
import sys
from PIL import Image, ImageDraw, ImageFont

FONTS = [
    # name,           ttf,                                              px, charset
    # Unit labels sitting beside a headline number.
    ("font_tiny",   "/System/Library/Fonts/Supplemental/Arial Bold.ttf", 10, None),
    ("font_small",  "/System/Library/Fonts/Supplemental/Arial Bold.ttf", 13, None),
    ("font_medium", "/System/Library/Fonts/Supplemental/Arial Bold.ttf", 21, None),
    # Screen titles, which get a full-width row of their own.
    ("font_title",  "/System/Library/Fonts/Supplemental/Arial Bold.ttf", 26, None),
    ("font_large",  "/System/Library/Fonts/Supplemental/Arial Bold.ttf", 56,
     "0123456789.:%- "),
    # Secondary readings: digits only, so the tables stay small.
    ("font_big",    "/System/Library/Fonts/Supplemental/Arial Bold.ttf", 32,
     "0123456789.:%- "),
    ("font_xl",     "/System/Library/Fonts/Supplemental/Arial Bold.ttf", 36,
     "0123456789.:%- "),
]

FULL = "".join(chr(c) for c in range(0x20, 0x7F))


PAD = 8


def render_glyph(font, size, ch):
    """Rasterise one glyph and locate its ink relative to the line top.

    Drawn onto a padded canvas with anchor "la", so (PAD, PAD) is the pen
    origin at the top of the ascender. Offsets are then measured directly off
    that canvas, which avoids depending on how getbbox/getmask report bounds.
    """
    canvas = Image.new("L", (size * 3 + PAD * 2, size * 3 + PAD * 2), 0)
    draw = ImageDraw.Draw(canvas)
    draw.text((PAD, PAD), ch, fill=255, font=font, anchor="la")

    box = canvas.getbbox()
    if box is None:                      # blank glyph, e.g. space
        return 0, 0, 0, 0, []

    x0, y0, x1, y1 = box
    rows = []
    for y in range(y0, y1):
        # Threshold at mid grey: e-paper is 1-bit, no dithering wanted.
        rows.append([1 if canvas.getpixel((x, y)) >= 128 else 0
                     for x in range(x0, x1)])

    return (x1 - x0, y1 - y0, x0 - PAD, y0 - PAD, rows)


def build(name, path, size, charset):
    font = ImageFont.truetype(path, size)
    chars = charset if charset else FULL
    first = min(ord(c) for c in chars)
    last = max(ord(c) for c in chars)

    ascent, descent = font.getmetrics()
    bitmap = bytearray()
    glyphs = []
    bits = []

    def flush():
        while len(bits) % 8:
            bits.append(0)
        for i in range(0, len(bits), 8):
            byte = 0
            for b in range(8):
                byte = (byte << 1) | bits[i + b]
            bitmap.append(byte)
        bits.clear()

    for code in range(first, last + 1):
        ch = chr(code)
        if ch not in chars:
            glyphs.append((len(bitmap), 0, 0, 0, 0, 0))
            continue

        w, h, xoff, yoff, rows = render_glyph(font, size, ch)
        offset = len(bitmap)
        for row in rows:
            bits.extend(row)
        flush()
        advance = int(round(font.getlength(ch)))
        glyphs.append((offset, w, h, advance, xoff, yoff))

    return {
        "name": name, "first": first, "last": last,
        "ascent": ascent, "yadvance": ascent + descent,
        "bitmap": bitmap, "glyphs": glyphs,
    }


def emit(fonts, out_c, out_h):
    with open(out_h, "w") as f:
        f.write("/* Generated by genfont.py - do not edit by hand.\n"
                " * Arial Bold rendered to 1-bit bitmaps at fixed pixel sizes.\n"
                " */\n#pragma once\n\n#include <stdint.h>\n\n")
        f.write("typedef struct {\n"
                "    uint16_t offset;   /* into the font's bitmap blob */\n"
                "    uint8_t width;\n"
                "    uint8_t height;\n"
                "    uint8_t advance;   /* pen movement for this glyph */\n"
                "    int8_t xoffset;\n"
                "    int8_t yoffset;    /* relative to the top of the line */\n"
                "} gfx_glyph_t;\n\n")
        f.write("typedef struct {\n"
                "    const uint8_t *bitmap;\n"
                "    const gfx_glyph_t *glyphs;\n"
                "    uint8_t first;\n"
                "    uint8_t last;\n"
                "    uint8_t ascent;    /* font ascent, informational */\n"
                "    uint8_t yadvance;  /* full line height */\n"
                "} gfx_font_t;\n\n")
        for fo in fonts:
            f.write("extern const gfx_font_t %s;\n" % fo["name"])

    with open(out_c, "w") as f:
        f.write('/* Generated by genfont.py - do not edit by hand. */\n')
        f.write('#include "fonts.h"\n\n')
        for fo in fonts:
            n = fo["name"]
            f.write("static const uint8_t %s_bitmap[] = {\n" % n)
            for i in range(0, len(fo["bitmap"]), 16):
                chunk = fo["bitmap"][i:i + 16]
                f.write("    " + " ".join("0x%02X," % b for b in chunk) + "\n")
            f.write("};\n\n")

            f.write("static const gfx_glyph_t %s_glyphs[] = {\n" % n)
            for idx, g in enumerate(fo["glyphs"]):
                code = fo["first"] + idx
                ch = chr(code)
                label = {"\\": "backslash", " ": "space"}.get(ch, ch)
                f.write("    {%5d, %3d, %3d, %3d, %4d, %4d},  /* %s */\n"
                        % (g[0], g[1], g[2], g[3], g[4], g[5], label))
            f.write("};\n\n")

            f.write("const gfx_font_t %s = {\n"
                    "    .bitmap = %s_bitmap,\n"
                    "    .glyphs = %s_glyphs,\n"
                    "    .first = 0x%02X,\n"
                    "    .last = 0x%02X,\n"
                    "    .ascent = %d,\n"
                    "    .yadvance = %d,\n"
                    "};\n\n" % (n, n, n, fo["first"], fo["last"],
                                fo["ascent"], fo["yadvance"]))


if __name__ == "__main__":
    built = [build(n, p, s, c) for n, p, s, c in FONTS]
    emit(built, sys.argv[1], sys.argv[2])
    for fo in built:
        print("%-12s %5d bytes bitmap, %3d glyphs, ascent %d, line %d"
              % (fo["name"], len(fo["bitmap"]), len(fo["glyphs"]),
                 fo["ascent"], fo["yadvance"]))
