/* Generated by genfont.py - do not edit by hand.
 * Arial Bold rendered to 1-bit bitmaps at fixed pixel sizes.
 */
#pragma once

#include <stdint.h>

typedef struct {
    uint16_t offset;   /* into the font's bitmap blob */
    uint8_t width;
    uint8_t height;
    uint8_t advance;   /* pen movement for this glyph */
    int8_t xoffset;
    int8_t yoffset;    /* relative to the top of the line */
} gfx_glyph_t;

typedef struct {
    const uint8_t *bitmap;
    const gfx_glyph_t *glyphs;
    uint8_t first;
    uint8_t last;
    uint8_t ascent;    /* font ascent, informational */
    uint8_t yadvance;  /* full line height */
} gfx_font_t;

extern const gfx_font_t font_tiny;
extern const gfx_font_t font_small;
extern const gfx_font_t font_medium;
extern const gfx_font_t font_title;
extern const gfx_font_t font_large;
extern const gfx_font_t font_big;
extern const gfx_font_t font_xl;
